fastai/course-v3

docs/start_salamander.md
I thought all ~3000 students were going to receive AWS credits, but now I've learned it's only 200 I'm happy to manually import all of their credits into Salamander on a 24h timescale if you'd like.
Tried automating to make instant but didn't finish.
=> Add "aws credits" subsection

docs/start_gcp.md
It is noted in the GCP [Storage Options](http://google.com) docs that "Performance on persistent disks is predictable, scales linearly, and is directly related to boot disk size. A boot disk smaller than 200GB will result in a poor experience."
=> Updated the boot disk size based on GCP advice

nbs/dl1/lesson1-pets.ipynb
I noticed that the first training example uses 4 iterations through the data - but the comment says 5.
=> Making markdown comment match code

docs/start_sagemaker.md
The current docs are lacking. 
The following breaks. 
1. Create notebook and start for the first time, all is well.
2. Stop Notebook.
3. Start Notebook.
4. Try to run notebook with any kernel attached. 
Fail :
" from fastai import *"
ModuleNotFoundError: No module named 'fastai'
This solves the issue.
TESTED restarted notebook, verified that this works and is broken without this.
=> Add docs, "Start Notebook" script. (import fastai on a restarted notebook now works)

docs/start_aws.md
I made two changes: 
1) Generating an ssh key requires typing 'ssh-keygen' into terminal (rather than just 'keygen')
2) You have to enter your ssh key into each region to be able to select an existing key pair when you launch an instance. Instructions are added to remind people to do this.
=> edit doc start_aws.md: ssh-keygen and check region

docs/update_gcp.md
The original `cd` command leads to error in the next step when calling git
```
jupyter@my-fastai-instance:~/tutorials/fastai$ git pull
fatal: Not a git repository (or any of the parent directories): .git
```
That is because we must go one level deeper - into `course-v3` subfolder.
=> Wrong 'cd' path before git

nbs/dl1/lesson3-planet.ipynb
(Please refer to the commit for code context)
Here `path` is `/home/jupyter/.fastai/data/planet`.
Recall that the default behavior of the `Path.mkdir` function will raise `FileNotFoundError` when there is a missing parent.
In a freshly installed new instance, there will not be a `data` directory under `.fastai` directory. Thus, the current command will raise `FileNotFoundError`.
Here is what the Python will raise:
`FileNotFoundError: [Errno 2] No such file or directory: '/home/jupyter/.fastai/data/planet'`
After adding an argument `parents=True`, any missing parents of this path are created as needed, which will produce the desired result in a new instance.
=> Updated lesson3-planet notebook

nbs/dl1/lesson3-planet.ipynb
fixing reference to deprecated code, ImageMultiDataset` and  `ImageClassificationDataset` are no longer parts of the library.
=> fixing reference to deprecated code

docs/css/customstyles.css, docs/deployment_render.md
The latest version of `fastai` works with the `.pkl` files generated by `.export`. Updating the docs to be current.
=> Update deployment docs to use the `.pkl` file 

docs/setup/colab
Not only is pytorch nightly not needed, but it gets overwritten when you install fastai later in the colab script.  Thus the user ends up downloading pytorch twice.  See issue #140
=> pytorch nightly no longer needed

docs/FAQ.md, docs/docs-dev-build.txt, docs/setup/sagemaker-cfn.yml, docs/start_aws.md, docs/start_azure.md, docs/start_colab.md, docs/start_crestle.md, docs/start_floydhub.md, docs/start_gcp.md, docs/start_gradient.md, docs/start_sagemaker.md, docs/start_salamander.md, docs/update_colab.md, files/dl-2019/notes/notes-1-1.md, files/dl-2019/notes/notes-1-2.md, files/dl-2019/notes/notes-1-3.md, nbs/dl1/00_notebook_tutorial.ipynb, nbs/dl1/lesson3-planet.ipynb
* Also switch all `http://course.fast.ai` links to `https://course.fast.ai`.
=> Replace course-v3 URLs

docs/start_gradient.md
I generated the promo code Dillon submitted last night but failed to make it Gradient° specific
This edit has a slightly different Gradient° Promo Code that IS Gradient°-specific
Also to avoid confusion from past expired codes, I added a note about when this one expires in line 88
=> Update Gradient° Promo Code

docs/gpu_tutorial.md
This reverts commit 8ecaedbecb2d5476f0743e6854e78e8d88a5abf5.
/images should be the correct location. Consistent with other tutorials
https://course.fast.ai/gpu_tutorial.html
=> Revert "fixed broken img link (#157)"

docs/start_gcp.md
Missing description if gpu quotas at 0. Added what to do. From:
https://stackoverflow.com/questions/53415180/gcp-error-quota-gpus-all-regions-exceeded-limit-0-0-globally
Improvement suggestions welcome.
=> Missing description if gpu quotas at 0

nbs/dl1/lesson2-download.ipynb
Mandatory 3rd argument `path` added to calls of `ImageCleaner`.
=> ImageCleaner: added missing required  argument

files/dl-2019/notes/notes-1-3.md
Changed : 
[Quick and easy model deployment] using Zeit 
to : 
[Quick and easy model deployment](https://course.fast.ai/deployment_render.html) using Render, 
because Zeit doesn't work anymore and has been removed from the course.fast.ai navigation bar. I did this because the presence of the link in the enriched content of the video made me think Zeit was working and I was doing something wrong (lost ~2-3 hours to this)
=> replaced Zeit by Render

files/dl-2019/notes/notes-1-4.md
If I understand ULMFiT correctly, we're *keeping* the encoder and concatenating it with a classifier. The original wording implies that we are deleting the encoder and replacing it with a classifier.
=> Improve wording for overview of ULMFiT

docs/setup/sagemaker-create
This change updates the `sagemaker-create` script to check the Cuda version and install the appropriate cudatoolkit and pytorch versions using conda.
Before this change, it took about 40 minutes to run the first `learn.fit_one_cycle(4)` call in lesson 1 of the 2019 deep-learning 1 course on my Sagemaker instance. After this change, it took 1m50s.
Before this change:
After this change:
If you check the installed/active Cuda version using a Terminal, you find:
```bash
sh-4.2$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
```
One thing I would ask of a reviewer - I wrote a bit of awk script to extract the active Cuda version and ask conda to use that version …
=> Install correct pytorch/cudatoolkit versions on sagemaker

nbs/dl1/rossman_data_clean.ipynb
Fixes issue in `rossman_data_clean.ipynb` reported in [this forum thread](https://forums.fast.ai/t/rossman-data-clean-ipynb-got-typeerror-dtype-class-datetime-datetime-not-understood/38936) where type error thrown during `datetime` type conversion.
=> Fix datetime type conversion in rossmann_data_clean nb

nbs/dl1/lesson2-download.ipynb
DatasetFormatter.from_toplosses removed the `ds_type` parameter.
In order to clean the whole dataset we need to create a separate
one with all the images. This commit alters the notebook
to reflect the new approach.
Some students, including myself, ran into an issue when ImageCleaner
didn't render at all. This happens when using Jupyter Lab instead
of Jupyter Notebook. I've added the warning to the notebook as well.
It also fixes an issue with creating ImageDataBunch from `cleaned.csv`.
The first param was `"."`, the current folder, but should be `path`.
This commit fixes it.
=> Updated usage of ImageCleaner

.gitmodules, cloudbuild.yaml
Functional tests that are replicating setup of the CI from here: https://github.com/b0noI/notebooks-ci-showcase
This commits covers only 2 notebooks:
* lesson2-sgd.ipynb (fast test done on top of the containers)
* lesson3-head-pose.ipynb (slower test done on top of the Deep Learning VM)
As soon as changes are in we can:
* to attache Cloud Build to the official origin
* to start covering other notebooks with tests (some of them are not yet self-contained, some of them need requires long term execution but can be parametrized)
* to start discussion on putting "open on GCP" button for notebooks that are covered with tests (since for covered notebooks we can guarantee with reasonable level of certainty that they are fully executable on GCP)
=> Functional Tests

nbs/dl1/lesson2-download.ipynb
Just add a single sentence to remind people before running javascript commands to get the URLs, first disable ads block add-ons such as YouBlock.
=> Remind people to disable ads block add-ons

nbs/dl1/lesson7-human-numbers.ipynb
Acc to the Lesson 7 video, Model1 is just the refactored version of Model0, but it is actually not, due to a missing self.hh term. 
This fix incorporates that term to make Model0 and Model1 equivalent.
=> Fixed a bug in Model0

nbs/dl1/lesson3-planet.ipynb
Installing libraries from python notebooks is actually not easy, but this should work for everybody whose user has access to site-packages.
=> Improve default command for installing libraries

docs/deployment_azure_functions.md
When building the docker image, there is an error: unable to execute 'gcc': No such file or directory. I add a quick fix for this issue.
=> Fix the gcc not found issue during building docker

docs/start_kaggle.md
Instructions to click on "Fork" button are incorrect, current button label is "Copy and Edit."
=> Updates instruction for how to fork notebook

nbs/dl2/notebook2script.py
Issue: When "exp" directory doesn't exists the script throw an exception!
Fix: Check for "exp" directory existence and if it doesn't exist, makes the directory.
=> Fix "No such file or directory" exception in notebook2script.py

files/dl-2019/notes/notes-2-8.md
Change `conda install -c fastai -c pytorch torch fastai` 
to `conda install -c fastai -c pytorch pytorch fastai`.
=> Fix command to install fastai and pytorch

nbs/dl2/07_batchnorm.ipynb
Mentioned in errata here https://github.com/fastai/course-v3/blob/master/files/dl-2019/notes/notes-2-10.md but not fixed in the notebook?
=> Fix .std to .var in layer & instance normalization

nbs/dl2/04_callbacks.ipynb
`learn.model.train()` (without `self.`) in method `begin_epoch` in class
`CallbackHandler` only worked because `learn = Learner(*get_model(data), loss_func, data)`
is globally defined.
Fix same problem in method `do_stop` in class `CallbackHandler`
and in method `after_step` in class `TestCallback`.
=> Add several missing `self.` in `CallbackHandler` class

nbs/dl1/lesson2-download.ipynb
Some lines of code were wrapped into the comments in the previous line, so they wouldn't appear to the user (and wouldn't run).
=> Missing carriage returns in notebook dl1/lesson2-download.ipynb

nbs/swift/01a_fastai_layers.ipynb
I honestly do not know if this should remain a link, as it is prone to changing again. Here is the fix if it still needs to be a link :)
=> Fixed dead link to Layer.swift

docs/start_gcp.md
The p4 GPUs are no longer available from GCP, so replaced with the p100
=> GCP tutorial - Change GPU type from p4 to p100

docs/update_colab.md
The image "/images/colab/07.png" showcasing the url to update Colab repo has been updated to  - 
"!curl https://course.fast.ai/setup/colab | bash"
from-  " !curl https://course-v3.fast.ai/setup/colab_update | bash ".
The image may either be removed or altered containing the new url.
=> Updating packages and course repo - Update

docs/start_gcp.md
The nvidia-tesla-p100 accelerator is not available in the gcloud us-west2-b zone, but is available in the us-west1-b zone (see https://cloud.google.com/compute/docs/gpus/#gpus-list). Not sure when this changed. Therefore, it appears that the us-west1-b zone should work for both regular and budget set-up options.
=> Update zone configuration for gcloud setup

docs/start_gcp.md
This change makes the language clearer based on the dropdowns in GCP:
=> Clarifying language in GCP tutorial

docs/start_azure.md
I was following these instructions and wasted some time reading docs on the Azure DSVM fastai extension when I didn't see the /fastai/ dir after initially connecting to JupyterHub.
Turns out all I had to do was wait a bit, since the extension installs asynchronously.
=> Update start_azure.md to clarify that sometimes patience is a virtue

nbs/dl1/lesson2-download.ipynb
Update comment specifying the use of the deprecated no_split() function, currently split_none() should be used.
=> Minor fix, update comment

docs/setup/colab, nbs/swift/08b_data_block_opencv.ipynb, nbs/swift/08c_data_block-lightlyfunctional.ipynb, nbs/swift/08c_data_block_generic.ipynb, nbs/swift/SwiftCV/install/compile_colab.sh, nbs/swift/SwiftCV/install/install_colab.sh, nbs/swift/SwiftCV/install/install_cv4.sh, nbs/swift/opencv_integration_example.ipynb
This change adds pre-built OpenCV v4 in Colab environment to solve problem with SwiftCV installation in some Swift notebooks:  https://forums.fast.ai/t/opencv-in-swift/44514/26
Details:
1. Added script `compile_colab.sh` to build and package opencv4 (this is for reference)
2. Using this script, `https://storage.googleapis.com/opencv4/opencv4.tgz` is created (using CPU Colab runtime)
3. `colab` script is updated to download & use compiled opencv4 binary
I've tested that SwiftCV notebook works when this binary is installed.
Note: it would be good to upload binary to other location (e.g. `https://course.fast.ai/setup/`) instead of `https://storage.googleapis.com/opencv4/opencv4.tgz` because this is my GCP bucket and I may eventually remove it.
=> Install pre-compiled OpenCV4 for Swift notebooks with OpenCV

nbs/dl2/05b_early_stopping.ipynb
Change `res = cb(cb_name) and res` to `res = cb(cb_name) or res`
so that `__call__` method does not always return `False` but returns
`True` if at least one of the callbacks returns `True`.
=> Fix faulty logic in __call__ method of Runner class, fixes #370

nbs/dl2/12a_awd_lstm.ipynb
Current:
```python
if len(h) > 1: ... apply TAR
```
However, `len(h)` gives the batch size and not the sequence length.
Should this be changed to the following?
```python
if h.size(1) > 1: ... apply TAR
```
=> Fix wrong dimension in Temporal Activation Regularization in RNNTrainer?

nbs/dl1/lesson2-download.ipynb
just some minor added info for the lesson 2 download notebook on to open the webconsole. The presented shortcuts are only valid for Google Chrome without mentioning that. I also added the shortcuts for Firefox.
=> add info about webconsole shortcuts

nbs/dl1/lesson2-download.ipynb
The current method doesn't work anymore.
=> Fix URL grab method for new Google images DOM

nbs/dl2/cyclegan.ipynb
I think the identity losses were flipped.
The original code has id_loss = ||G(A) - A||
https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/690470c80bb7021d96c9d3f82e416e633dbb2da3/models/cycle_gan_model.py#L158
The notebook had ||G(A) - B||
=> Updating cyclegan identity loss

docs/start_gcp.md
- Updates the standard compute setup from `n1-highmem-8` to `n2d-highmem-8` (52 --> 64 GB memory, Intel --> AMD)
- Updates the budget compute setup from `n1-highmem-4` to `n2d-highmem-4` (26 --> 32 GB memory, Intel --> AMD)
- Updates both the standard P4 and budget K80 GPU to the cheaper and faster T4 GPU.
- Updates storage pricing
- Add an option for fast SSD storage
=> Docs: Update Google Cloud products and pricing

docs/start_gcp.md
Small update following #488. GPUs aren't available on N2 and N2D instances, so this PR switches it back to N1 instances. Thanks to @danfrankj for reporting this issue.
=> Docs: Update Google Cloud products and pricing (2)

docs/deployment_flask_gunicorn_docker.md
the image I put on repo appears broken, looks like I had to put /docs/images instead of just /images
=> correct link to image in repo, adding /docs in front of /images

docs/start_gcp.md
Just changed # budget: 'type=nvidia-tesla-T4,count=1' to # budget: 'type=nvidia-tesla-t4,count=1'
this way the user don't go to error, as copying and pasting the first one doesn't work
=> correct line 124

docs/update_gcp.md
Running 
```
sudo /opt/anaconda3/bin/conda install -c fastai fastai
```
resulted in an ```command not found``` error 
Instead running ```sudo /opt/anaconda3/bin/conda install -c fastai fastai``` updated the library.
=> Small fix on path for fast.ai library update

nbs/dl2/05_anneal.ipynb
IndexError: index 3 is out of bounds for dimension 0 with size 3
torch.linspace() behaviour differs in different PyTorch versions. 
For example, for T = torch.linspace(0.01, 1, 100),
value of T[99] is 0.99XXXXXX in version 1.4.0
value of T[99] is 1 in torch versions > 1.4.0
Hence modified the function def _inner() by adding 'if idx == 2: idx = 1' to work as expected.
=> Fix for the error, IndexError: index 3 is out of bounds for dimension 0 with size 3,  in 05_anneal.ipynb

nbs/dl2/05b_early_stopping.ipynb
[in_train] variable is missing in the notebook version of the Runner class. Can cause problems if exported.
=> Add missing [in_train] variable specification

docs/start_gcp.md
The location of conda seems to have been updated in the `deeplearning-platform-release` image on Google.
Here's the new location:
```
jupyter@my-fastai-instance:~/tutorials/fastai/course-v3$ which conda
/opt/conda/bin/conda
```
=> Small change to the location of conda in GCP docs

docs/_data/sidebars/home_sidebar.yml, docs/deployment_kubernetes_docker.md
Add the Kubernetes deployment guide for fastai.  Include how to build a model server with BentoML, build the model server docker image, and deploy to Kubernetes.
Feel free to ping me, if there are any questions I can help with.
=> Add kubernetes deployment guide for Fastai

docs/deployment_zeit.md
- Zeit just rebranded to Vercel and this PR changes the deployment guidelines to deployment for gridsome
=> [FIX] switch zeit now to Vercel Now for fastai

docs/start_gcp.md
The current documentation describes instance and zone combinations as well as a GPU instance that are incompatible. The suggested instances are as close to the original as possible. The prices have also been updated to more accurately reflect the cost of running this. Finally the conda command needed to be updated, as it was giving an error using the current code. This is well documented in the forum (https://forums.fast.ai/t/platform-gcp/27375/703) and as an issue (https://github.com/fastai/course-v3/issues/493). Includes changing the zone because T4 and P100 are not supported in the previously listed zone; as such, this pull request will still fail (https://github.com/fastai/course-v3/pull/495).
=> Update GCP docs to usable instances and zone

docs/deployment_render.md
Users currently have to read through the fast.ai forum Render thread if they run into an error deploying because of the package versions used in the requirements.txt file. Given that this seems to be a very common issue, I suggest that this instruction be added to the documentation.
=> add instructions for updating requirements.txt

docs/start_colab.md
The old link https://course.fast.ai/setup/colab is not accessible.
=> Update setup colab link in start_colab.md
